config/routes.rb
Rails.application.routes.draw do

  namespace :user do
    get 'relationships/followings'
    get 'relationships/followers'
  end
  namespace :admin do
    get 'homes/top'
  end
  # ユーザー用
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # 管理者
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :reviews, only: [:index, :show, :edit, :update, :destroy]
    resources :movies, only: [:index, :show, :edit, :update, :destroy]
    resources :comments, only: [:index, :edit, :update, :destroy]
    #退会機能
    patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
    patch '/users/:id/cancel' => 'users#cancel', as: 'cancel'

    #検索機能
    get "search" => "searches#search"

    get 'followings/:user_id' => 'relationships#followings', as: 'followings'
    get 'followers/:user_id' => 'relationships#followers', as: 'followers'

  end

  # ユーザー
  scope module: :user do
    root :to => "homes#top"
    get "reviews/index" => "reviews/index"
    resources :movies, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
      resources :reviews, only: [:create]
      resource :favorites, only: [:create, :destroy]
    end
    resources :reviews, only: [:show, :edit, :update, :destroy] do
      resources :comments, only: [:create]
    end
    resources :comments, only: [:edit, :update, :destroy]

    resources :users, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end

    #退会機能
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'

    #検索機能
    get "search" => "searches#search"

  end



end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_one_attached :image

  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  validates :title, presence: true
  validates :body, presence: true
  validates :image, presence: true

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @movie = Movie.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @movie = Movie.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @movie = Movie.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @movie = Movie.where("title LIKE?","%#{word}%")
    else
      @movie = Movie.all
    end
  end
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  has_one_attached :image
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  has_many :comments, dependent: :destroy

 validates :star, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1}, presence: true

  validates :title, presence: true
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.png')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # 退会済みユーザーがログインできないようにis_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end

  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  def index
    @reviews = Review.page(params[:page]).per(10)
  end

  def show
    @review = Review.find(params[:id])
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    review = Review.find(params[:id])
    review.update(review_params)
    redirect_to admin_reviews_path
  end

  def destroy
    Review.find(params[:id]).destroy
    redirect_to admin_reviews_path
  end

  private
  def review_params
    params.require(:review).permit(:title, :body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/user/reviews_controller.rb
class User::ReviewsController < ApplicationController

  def create
    movie = Movie.find(params[:movie_id])
    review = Review.new(review_params)
    review.user_id = current_user.id
    review.movie_id = movie.id

    review.save
    redirect_to movie_path(movie.id)
  end

  def show
    @review = Review.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @review = Review.find(params[:id])
    unless @review.user == current_user
      redirect_to  root_path
    end
  end

  def update
    review = Review.find(params[:id])
    review.update(review_params)
    redirect_to movie_path(review.movie.id)
  end

  def index
    @reviews = Review.page(params[:page]).per(10)
  end

  def destroy
    review = Review.find(params[:id])
    Review.find(params[:id]).destroy
    redirect_to movie_path(review.movie.id)
  end

  private
  def review_params
    params.require(:review).permit(:title, :body, :star)
  end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/movies_helper.rb
module Admin::MoviesHelper
end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user/comment_helper.rb
module User::CommentHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/movies_helper.rb
module User::MoviesHelper
end

app/helpers/user/reviews_helper.rb
module User::ReviewsHelper
end

app/helpers/user/searches_helper.rb
module User::SearchesHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/admin/reviews/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>タイトル</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= link_to admin_movie_path(review.movie.id) do %>
          <%= image_tag review.movie.image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to review.movie.title, admin_movie_path(review.movie.id) %></td>
        <td><%= link_to review.title, admin_review_path(review.id) %></td>
        <td><%= review.created_at.strftime('%Y/%m/%d') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/reviews/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>映画レビュー編集(管理者)</h2>
    <%= form_with model:@review, url:admin_review_path(@review.id), local:true do |f| %>
      <div class="form-group">
        <%= f.label :タイトル %>
        <%= f.text_field :title, class: "form-control title" %>
      </div>
      <div class="form-group">
        <%= f.label :レビュー %>
        <%= f.text_area :body, class: "form-control body" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/reviews/index.html.erb
<div class='col-md-8 offset-md-1'>
  <h2>レビュー一覧：<%= @reviews.count %>件</h2>
  <%= render 'index', reivews: @reviews%>
  <%= paginate(@reviews) %>
</div>

app/views/admin/reviews/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-10 offset-md-1'>
    	<h2><%= @review.movie.title %></h2>
    	<table class='table'>
    	  <tr>
         <td><%= image_tag @review.movie.image, size:'200x200' %></td>
         <td><%= @review.movie.body %></td>
        </tr>
      </table>
      レビュー
      <table class="table">
        <tr>
          <td>
            <%= link_to image_tag(@review.user.get_profile_image(50,50)), admin_user_path(@review.user) %>
            <%= link_to @review.user.name, admin_user_path(@review.user) %>
          </td>
          <td>
            <%= @review.title %>
          </td>
          <td>
					  <%#星評価%>
            <p>評価 :<%= @review.star%>点</p>
              <div id="star-rate<%= @review.id%>"></div>
              <script>
                $('#star-rate<%= @review.id%>').raty({
                  size      : 36,
                  starOff   : '<%= asset_path('star-off.png') %>',
                  starOn    : '<%= asset_path('star-on.png') %>',
                  starHalf: '<%= asset_path('star-half.png') %>',
                  half      : true,
                  readOnly: true,
                  score: <%= @review.star %>,
                });
              </script>
              </div>
		    	</td>
          <td>
            <% if current_admin %>
              <%= link_to "編集", edit_admin_review_path(@review), class: "btn-sm btn-success" %>
              <%= link_to "削除", admin_review_path(@review.id), method: :delete, "data-confirm" => "本当に削除しますか？",class: "btn-sm btn-danger" %>
            <% end %>
          </td>
        </tr>
      </table>
      <table>
        <tr>
          <td>
            <%= @review.body %>
          </td>
        </tr>
      </table>
      <table class="table">
        レビューへのコメント：<%= @review.comments.count %>件
    			<% @review.comments.each do |comment|%>
		    <tr>
		    	<td>
		    		<%= link_to image_tag(comment.user.get_profile_image(50,50)), admin_user_path(comment.user) %>
			    	<%= link_to comment.user.name, admin_user_path(comment.user) %>
			    </td>
    			<td>
	    			<%= comment.comment %>
	    		</td>
	    		<td>
	    			<% if current_admin %>
		    		<%= link_to "編集", edit_admin_comment_path(comment), class: "btn-sm btn-success" %>
	    			<%= link_to "削除", admin_comment_path(comment.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn-sm btn-danger" %>
	    			<% end %>
	    		</td>
    		</tr>
    			<% end %>
    	</table>
    </div>
  </div>
</div>