config/routes.rb
Rails.application.routes.draw do

  namespace :user do
    get 'relationships/followings'
    get 'relationships/followers'
  end
  namespace :admin do
    get 'homes/top'
  end
  # ユーザー用
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # 管理者
  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update]
    resources :reviews, only: [:index, :show, :edit, :update, :destroy]
    resources :movies, only: [:index, :show, :edit, :update, :destroy]
    resources :comments, only: [:index, :edit, :update, :destroy]
    #退会機能
    patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
    patch '/users/:id/cancel' => 'users#cancel', as: 'cancel'

    #検索機能
    get "search" => "searches#search"

    get 'followings/:user_id' => 'relationships#followings', as: 'followings'
    get 'followers/:user_id' => 'relationships#followers', as: 'followers'

  end

  # ユーザー
  scope module: :user do
    root :to => "homes#top"
    get "reviews/index" => "reviews/index"
    resources :movies, only: [:new, :index, :show, :edit, :create, :update, :destroy] do
      resources :reviews, only: [:create]
      resource :favorites, only: [:create, :destroy]
    end
    resources :reviews, only: [:show, :edit, :update, :destroy] do
      resources :comments, only: [:create]
    end
    resources :comments, only: [:edit, :update, :destroy]

    resources :users, only: [:index, :show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end

    #退会機能
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'

    #検索機能
    get "search" => "searches#search"

  end



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.png')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # 退会済みユーザーがログインできないようにis_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end

  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to admin_user_path(user.id)
  end

  def unsubscribe
    @user = User.find(params[:id])
  end

  def withdrawal
    @user = User.find(params[:id])
    @user.update(is_deleted: true)
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to admin_user_path(@user)
  end

  def cancel
    @user = User.find(params[:id])
    @user.update(is_deleted: false)
    flash[:notice] = "退会取り消し処理を実行いたしました"
    redirect_to admin_user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController

  def create
    review = Review.find(params[:review_id])
    comment = Comment.new(comment_params)
    comment.user_id = current_user.id
    comment.review_id = review.id
    comment.save
    redirect_to review_path(review.id)
  end

  def edit
    @comment = Comment.find(params[:id])
    unless @comment.user == current_user
      redirect_to  root_path
    end
  end

  def update
    comment = Comment.find(params[:id])
    comment.update(comment_params)
    redirect_to review_path(comment.review.id)
  end

  def destroy
    comment = Comment.find(params[:id])
    Comment.find(params[:id]).destroy
    redirect_to review_path(comment.review.id)
  end

  private
  def comment_params
    params.require(:comment).permit(:comment)
  end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController

  def create
    movie = Movie.find(params[:movie_id])
    @favorite = current_user.favorites.new(movie_id: movie.id)
    @favorite.save
  end

  def destroy
    movie = Movie.find(params[:movie_id])
    @favorite = current_user.favorites.find_by(movie_id: movie.id)
    @favorite.destroy
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
    @movies = Movie.order(created_at: :desc).limit(3)
    @reviews = Review.order(created_at: :desc).limit(3)
  end
end

app/controllers/user/movies_controller.rb
class User::MoviesController < ApplicationController
  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movie_path(@movie.id)
    else
      render :new
    end
  end

  def index
    @movies = Movie.page(params[:page]).per(10)
  end

  def show
    @movie = Movie.find(params[:id])
    @review = Review.new
    @reviews = Review.all
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    movie = Movie.find(params[:id])
    movie.update(movie_params)
    redirect_to movie_path(movie.id)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to "/movies"
  end

  private
  def movie_params
    params.require(:movie).permit(:title, :body, :image)
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/post_images_controller.rb
class User::PostImagesController < ApplicationController
  def new
  end

  def create
  end

  def index
  end

  def show
  end

  def destroy
  end

end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/relationships_controller.rb
class User::RelationshipsController < ApplicationController
  # フォローするとき
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  # フォロー外すとき
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end
  # フォロー一覧
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end
  # フォロワー一覧
  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/user/reviews_controller.rb
class User::ReviewsController < ApplicationController

  def create
    movie = Movie.find(params[:movie_id])
    review = Review.new(review_params)
    review.user_id = current_user.id
    review.movie_id = movie.id

    review.save
    redirect_to movie_path(movie.id)
  end

  def show
    @review = Review.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @review = Review.find(params[:id])
    unless @review.user == current_user
      redirect_to  root_path
    end
  end

  def update
    review = Review.find(params[:id])
    review.update(review_params)
    redirect_to movie_path(review.movie.id)
  end

  def index
    @reviews = Review.page(params[:page]).per(10)
  end

  def destroy
    review = Review.find(params[:id])
    Review.find(params[:id]).destroy
    redirect_to movie_path(review.movie.id)
  end

  private
  def review_params
    params.require(:review).permit(:title, :body, :star)
  end

end

app/controllers/user/searches_controller.rb
class User::SearchesController < ApplicationController

  def search
    @range = params[:range]
    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @movies = Movie.looks(params[:search], params[:word])
    end
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :user_state, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  protected
    def user_state
      @user = User.find_by(email: params[:user][:email])
      return if !@user
      if @user.valid_password?(params[:user][:password]) && @user.is_deleted
        flash[:error] = "退会済みユーザーです。新規登録をお願いします。"
        redirect_to new_user_registration_path
      else
        flash[:error] = "必須項目を入力してください。"
      end
    end

    def after_sign_in_path_for(resource)
      root_path
    end

    def after_sign_out_path_for(resource)
      root_path
    end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  def index
    @users = User.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    redirect_to user_path(user.id)
  end

  def unsubscribe
  end

  def withdrawal
    @user = User.find(params[:id])
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :favolite_movie, :introduction)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/comment_helper.rb
module User::CommentHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/views/user/users/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>ユーザー名</th>
      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <% if user.is_deleted %>
      <% else %>
        <tr>
          <td><%= link_to user_path(user.id) do %>
            <%= image_tag user.get_profile_image(50,50) %>
            <% end %>
          </td>
          <td><%= link_to user.name,user, class: "user_#{user.id}" %></td>
          <td>
					  <p>レビュー数：<%= user.reviews.count %></p>
				  </td>
				  <td><%= user.followers.count %>フォロワー</td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/user/users/_info.html.erb
<% if current_user %>
  <table class='table'>
    <tr><%= image_tag user.get_profile_image(100,100) %></tr>
    <tr>
	    <th>ユーザー名</th>
	    <th><%= user.name %></th>
    </tr>
    <tr>
      <th>好きな映画</th>
      <th><%= user.favolite_movie %></th>
    </tr>
    <tr>
	    <th>自己紹介</th>
	    <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th>レビュー数</th>
      <th><%= user.reviews.count %></th>
    </tr>
    <tr>
		  <th>フォロー</th>
		  <th><%=link_to user.followings.count, user_followings_path(user.id) %></th>
	  </tr>
	  <tr>
		  <th>フォロワー</th>
		  <th><%=link_to user.followers.count, user_followers_path(user.id) %></th>
	  </tr>
  </table>

  <div class='row'>
    <% if current_user != user %>
      <% if current_user.following?(user) %>
        <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-danger btn-sm btn-block" %>
      <% else %>
        <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success btn-sm btn-block" %>
      <% end %>
    <% else %>
      <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
        <i class="fas fa-edit"></i>ユーザー情報編集
      <% end %>
      <%= link_to unsubscribe_path(user), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fa fa-trash"></i>退会
      <% end %>
    <% end %>
  </div>
<% else %>
  <table class='table'>
    <tr>
	    <th>ゲストユーザー</th>
    </tr>
  </table>
<% end %>

app/views/user/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :favolite_movie %>
        <%= f.text_area :favolite_movie, class: "form-control favolite_movie" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/user/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'user/users/info', user: current_user %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>ユーザー一覧</h2>
      <%= render 'index', users: @users%>
      <%= paginate(@users) %>
    </div>
  </div>
</div>

app/views/user/users/show.html.erb
<div class='container'>
  <div class='row'>
    <% if @user.is_deleted %>
      <div class='col-md-8 offset-md-2 text-center'>
        <h1>このユーザーは退会済です</h1>
      </div>
    <% else %>
    <div class='col-md-3'>
      <h2>ユーザー詳細</h2>
      <table class='table'>
          <tr><%= image_tag @user.get_profile_image(100,100) %></tr>
          <tr>
      	    <th>ユーザー名</th>
        	  <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>好きな映画</th>
            <th><%= @user.favolite_movie %></th>
          </tr>
          <tr>
        	  <th>自己紹介</th>
        	  <th><%= @user.introduction %></th>
          </tr>
          <tr>
            <th>レビュー数</th>
            <th><%= @user.reviews.count %></th>
          </tr>
          <tr>
      	  	<th>フォロー</th>
         		<th><%=link_to @user.followings.count, user_followings_path(@user.id) %></th>
        	</tr>
        	<tr>
        		<th>フォロワー</th>
	        	<th><%=link_to @user.followers.count, user_followers_path(@user.id) %></th>
         	</tr>

      </table>
      <div class='row'>
        <% if current_user %>
          <% if current_user != @user %>
            <% if current_user.following?(@user) %>
              <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete, class: "btn btn-danger btn-sm btn-block" %>
            <% else %>
               <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "btn btn-success btn-sm btn-block" %>
            <% end %>
          <% else %>
            <%= link_to edit_user_path(@user), class: "btn btn-outline-secondary btn-block edit_user_#{@user.id}" do %>
              <i class="fas fa-edit"></i>ユーザー情報編集
            <% end %>
            <%= link_to unsubscribe_path(@user), class: "btn btn-outline-secondary btn-block" do %>
              <i class="fa fa-trash"></i>退会
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2><%= @user.name %>のレビュー一覧</h2>
      <table class="table">
					<% @user.reviews.each do |review|%>
				<tr>
					<td><%= link_to movie_path(review.movie) do %>
					  <%= image_tag review.movie.image, size:'50x50' %>
					  <% end %>
						<%= link_to review.movie.title, movie_path(review.movie) %>
					</td>
					<td>
						<%= link_to review.title, review_path(review.id)%>
					</td>
					<td>
					<% if current_user %>
						<% if review.user_id == current_user.id %>
						  <%= link_to "編集", edit_review_path(review), class: "btn-sm btn-success" %>
						  <%= link_to "削除", review_path(review.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn-sm btn-danger" %>
						<% end %>
					<% end %>
					</td>
				</tr>
					<% end %>
			</table>
    </div>
    <% end %>
  </div>
</div>

app/views/user/users/unsubscribe.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>退会お手続き</h2>
      <p>
        退会手続きをされますと、全てのサービスがご利用いただけなくなります。<br>
        再度ご利用をいただく場合には、新規登録のお手続きが必要になります。<br>
        本当に退会してよろしいですか？
      </p>
        <%= link_to "退会する", withdrawal_path, class: "btn-sm btn-success", method: :patch, data: { confilm: "本当に退会しますか？" } %>
        <%= link_to "退会しない", user_path(current_user), class: "btn-sm btn-danger" %>
    </div>
  </div>
</div>